-- Allow user creation
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- Create user
CREATE USER RESERVATION IDENTIFIED BY MANAGER;

GRANT DBA TO RESERVATION;

-- IMPORTANT: force connect (works in gvenzl image)
CONNECT RESERVATION/MANAGER;

-- Now everything runs under RESERVATION automatically

CREATE TABLE CUSTOMER 
(
  MAILID VARCHAR2(40) PRIMARY KEY,
  PWORD VARCHAR2(20) NOT NULL,
  FNAME VARCHAR2(20) NOT NULL,
  LNAME VARCHAR2(20),
  ADDR VARCHAR2(100),
  PHNO NUMBER(12) NOT NULL
);

CREATE TABLE ADMIN
(
  MAILID VARCHAR2(40) PRIMARY KEY,
  PWORD VARCHAR2(20) NOT NULL,
  FNAME VARCHAR2(20) NOT NULL,
  LNAME VARCHAR2(20),
  ADDR VARCHAR2(100),
  PHNO NUMBER(12) NOT NULL
);

CREATE TABLE TRAIN 
(
  TR_NO NUMBER(10) PRIMARY KEY,
  TR_NAME VARCHAR2(70) NOT NULL,
  FROM_STN VARCHAR2(20) NOT NULL,
  TO_STN VARCHAR2(20) NOT NULL,
  SEATS NUMBER(4) NOT NULL,
  FARE NUMBER(6,2) NOT NULL
);

CREATE TABLE HISTORY 
(
  TRANSID VARCHAR2(36) PRIMARY KEY,
  MAILID VARCHAR2(40),
  TR_NO NUMBER(10),
  DATE_OF_BOOKING DATE,
  FROM_STN VARCHAR2(20) NOT NULL,
  TO_STN VARCHAR2(20) NOT NULL,
  SEATS NUMBER(3) NOT NULL,
  AMOUNT NUMBER(8,2) NOT NULL,
  CONSTRAINT FK_HISTORY_CUSTOMER
    FOREIGN KEY (MAILID) REFERENCES CUSTOMER(MAILID)
);

-- seed data
INSERT INTO ADMIN VALUES
('admin@demo.com','admin','System','Admin','Demo Address','9874561230');

INSERT INTO CUSTOMER VALUES
('shashi@demo.com','shashi','Shashi','Raj','Kolkata',954745222);

INSERT INTO TRAIN VALUES(10001,'JODHPUR EXP','HOWRAH','JODHPUR',152,490.50);
INSERT INTO TRAIN VALUES(10002,'YAMUNA EXP','GAYA','DELHI',52,550.50);
INSERT INTO TRAIN VALUES(10003,'NILANCHAL EXP','GAYA','HOWRAH',92,451);

COMMIT;
