username=RESERVATION
password=MANAGER
driverName = oracle.jdbc.driver.OracleDriver
#connectionString=jdbc:oracle:thin:@oracle-db:1521/XEPDB1
#connectionString=jdbc:oracle:thin:@localhost:1521:orcl
